1. 

PREFIX terms: <http://purl.org/dc/terms/>

SELECT ?name, ?comment 
WHERE {

{ ?subject a <http://dbpedia.org/ontology/Disease> . }

UNION 

{ ?subject terms:subject <http://dbpedia.org/resource/Category:Medical_signs> . }


?subject dbpedia2:name ?name . 
?subject rdfs:comment ?comment .

FILTER(regex(?name, "urticaria", "i"))
FILTER(lang(?name) = "en")
FILTER(lang(?comment) = "en")
}
ORDER BY strlen(?name)
LIMIT 1

2. 

PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX terms: <http://purl.org/dc/terms/>

SELECT DISTINCT *
WHERE {

   {
      ?s skos:broader <http://dbpedia.org/resource/Category:Symptoms_and_signs>  .
      ?s2 terms:subject ?s .
      ?s2 rdfs:label ?label . 
      ?s2 rdfs:comment ?comment .
   
      FILTER (regex(?label, "urticaria", "i"))
      FILTER (lang(?label) = "en")
      FILTER (lang(?comment) = "en")   
   }

   UNION

   {
      ?s rdf:type dbo:Disease .
      ?s rdfs:label ?label . 
      ?s rdfs:comment ?comment .
   
      FILTER (regex(?label, "urticaria", "i"))
      FILTER (lang(?label) = "en")
      FILTER (lang(?comment) = "en")
   }

   UNION

   {
      ?s rdf:type dbo:Disease .
      ?s rdfs:label ?label . 
      ?s rdfs:comment ?comment .
      ?s2 dbo:wikiPageRedirects ?s
   
      FILTER (regex(?s2, "urticaria", "i"))
      FILTER (lang(?label) = "en")
      FILTER (lang(?comment) = "en")
   }
   
}
LIMIT 1
